from kidney_disease_classfication.components.data_ingestion import DataIngestion
from kidney_disease_classfication.components.data_transformation import DataTransformation
from kidney_disease_classfication.components.model_trainer import ModelTrainer
from kidney_disease_classfication.components.model_evaluation import ModelEvaluation
