# Active models to train and evaluate in the pipeline
models_to_train:
  - LogisticRegression
  - LinearSVC
  - MultinomialNB
  - RidgeClassifier
  - XGBoost
  - DistilBERT

# Shared global configurations
random_state: 42
max_features: 15000

# Model-specific hyperparameters
LogisticRegression:
  C: 1.0
  solver: "lbfgs"
  max_iter: 100

LinearSVC:
  C: 1.0
  loss: "squared_hinge"
  max_iter: 1000

MultinomialNB:
  alpha: 0.1

RidgeClassifier:
  alpha: 1.0

XGBoost:
  n_estimators: 80
  max_depth: 5
  learning_rate: 0.15

DistilBERT:
  epochs: 1
  batch_size: 32
  learning_rate: 0.00002
  max_len: 128
