artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: Kidney_diesease-classificiation/dataset/thoroughly_cleaned_data.csv
  local_data_file: artifacts/data_ingestion/tweet_sentiment.csv
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  report_file: artifacts/data_validation/report.json

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_transformation/train_cleaned.csv
  test_data_path: artifacts/data_transformation/test_cleaned.csv
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl
  tokenizer_path: artifacts/data_transformation/tokenizer

model_trainer:
  root_dir: artifacts/model_trainer
  model_dir: artifacts/model_trainer/models

model_evaluation:
  root_dir: artifacts/model_evaluation
  metrics_dir: artifacts/model_evaluation/metrics

best_model_selector:
  root_dir: artifacts/best_model_selector
  best_model_path: artifacts/best_model_selector/best_model.pkl
  metadata_path: artifacts/best_model_selector/best_model_metadata.json

database:
  db_url: sqlite:///artifacts/sentiment_platform.db
